name: Tags
on:
  create:
    tags:
      - v*
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: Klemensas/chrome-extension-upload-action@$VERSION
        with:
          refresh-token: 'xxxxxxxxxxxxxxxxxxxxxx'
          client-id: 'xxxxxxxxxxxxx'
          client-secret: 'xxxxxxxxxxxx'
          file-name: './extension.zip'
          app-id: 'mphkdfmipddgfobjhphabphmpdckgfhb'
          publish: true
